<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Seeder class for the jurusan table.
 * Generated by Laravel DB Craft.
 * Generated on: 2026-06-11 13:32:15
 */
class JurusanTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Disable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        
        // Truncate the table
        DB::table('jurusan')->truncate();
        
        // Insert data in chunks
        DB::table('jurusan')->insert([
            [
                'id' => 1,
                'kode_jurusan' => 'PPLG',
                'nama_jurusan' => 'PENGEMBANGAN PERANGKAT LUNAK DAN GIM',
                'created_at' => '2026-06-08 09:35:33',
                'updated_at' => '2026-06-08 09:35:33',
            ],
            [
                'id' => 2,
                'kode_jurusan' => 'AKL',
                'nama_jurusan' => 'AKUNTANSI KEUANGAN LEMBAGA',
                'created_at' => '2026-06-11 04:05:59',
                'updated_at' => '2026-06-11 04:05:59',
            ],
            [
                'id' => 3,
                'kode_jurusan' => 'TJKT',
                'nama_jurusan' => 'TEKNIK JARINGAN KOMUTER TELEKOMUNIKASI',
                'created_at' => '2026-06-11 04:06:54',
                'updated_at' => '2026-06-11 04:06:54',
            ],
            [
                'id' => 4,
                'kode_jurusan' => 'ACP',
                'nama_jurusan' => 'AXIO CLASS PROGRAM',
                'created_at' => '2026-06-11 04:07:15',
                'updated_at' => '2026-06-11 04:07:27',
            ],
        ]);
        
        // Re-enable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}