<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Seeder class for the kelas table.
 * Generated by Laravel DB Craft.
 * Generated on: 2026-06-11 13:32:15
 */
class KelasTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Disable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        
        // Truncate the table
        DB::table('kelas')->truncate();
        
        // Insert data in chunks
        DB::table('jurusan')->insert([
            [
                'id' => 3,
                'nama_kelas' => 'XI 1',
                'tingkat' => 11,
                'created_at' => '2026-06-08 09:37:53',
                'updated_at' => '2026-06-11 04:10:39',
            ],
            [
                'id' => 4,
                'nama_kelas' => 'X 1',
                'tingkat' => 10,
                'created_at' => '2026-06-11 04:09:20',
                'updated_at' => '2026-06-11 04:14:00',
            ],
            [
                'id' => 5,
                'nama_kelas' => 'XII 1',
                'tingkat' => 12,
                'created_at' => '2026-06-11 04:09:30',
                'updated_at' => '2026-06-11 04:14:13',
            ],
            [
                'id' => 6,
                'nama_kelas' => 'XI 2',
                'tingkat' => 11,
                'created_at' => '2026-06-11 04:13:52',
                'updated_at' => '2026-06-11 04:13:52',
            ],
            [
                'id' => 7,
                'nama_kelas' => 'X 2',
                'tingkat' => 10,
                'created_at' => '2026-06-11 04:14:08',
                'updated_at' => '2026-06-11 04:14:08',
            ],
            [
                'id' => 8,
                'nama_kelas' => 'XII 2',
                'tingkat' => 12,
                'created_at' => '2026-06-11 04:14:21',
                'updated_at' => '2026-06-11 04:14:21',
            ],
        ]);
        
        // Re-enable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}