<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Seeder class for the sessions table.
 * Generated by Laravel DB Craft.
 * Generated on: 2026-06-11 13:32:15
 */
class SessionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Disable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        
        // Truncate the table
        DB::table('sessions')->truncate();
        
        // Insert data in chunks
        DB::table('kelas')->insert([
            [
                'id' => '5pSdglvHKXFFPktyAIEP2UbIiM6rAn3WGwYZLkNz',
                'user_id' => 1,
                'ip_address' => '127.0.0.1',
                'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36 Edg/142.0.0.0',
                'payload' => 'eyJfdG9rZW4iOiI0eHBaOXpOajFLV0pwc1o5Z05YTU5adG9qNGk1UkNsRThKOHhyTEluIiwiX2ZsYXNoIjp7Im9sZCI6W10sIm5ldyI6W119LCJfcHJldmlvdXMiOnsidXJsIjoiaHR0cDpcL1wvMTI3LjAuMC4xOjgwMDBcL3RhZ2loYW5cL2J1bGsiLCJyb3V0ZSI6InRhZ2loYW4uYnVsayJ9LCJsb2dpbl93ZWJfNTliYTM2YWRkYzJiMmY5NDAxNTgwZjAxNGM3ZjU4ZWE0ZTMwOTg5ZCI6MX0=',
                'last_activity' => 1781152020,
            ],
            [
                'id' => 'Ka1TezWmG1O0kXRoIfWLJTr9zbEdUcLfQYPbxr1Y',
                'user_id' => null,
                'ip_address' => '127.0.0.1',
                'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.123.0 Chrome/148.0.7778.97 Electron/42.2.0 Safari/537.36',
                'payload' => 'eyJfdG9rZW4iOiJaQ1VaZk1vTmdwQzdjMktIcEhuWUh4djYwaGJJQk5zQ3ZyV3A3SzQzIiwiX3ByZXZpb3VzIjp7InVybCI6Imh0dHA6XC9cLzEyNy4wLjAuMTo4MDAwXC9sb2dpbiIsInJvdXRlIjoibG9naW4ifSwiX2ZsYXNoIjp7Im9sZCI6W10sIm5ldyI6W119fQ==',
                'last_activity' => 1781148506,
            ],
        ]);
        
        // Re-enable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}