<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Seeder class for the spp table.
 * Generated by Laravel DB Craft.
 * Generated on: 2026-06-11 13:32:15
 */
class SppTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Disable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        
        // Truncate the table
        DB::table('spp')->truncate();
        
        // Insert data in chunks
        DB::table('sessions')->insert([
            [
                'id' => 4,
                'tahun' => '2025/2026',
                'nominal' => 450000,
                'keterangan' => 'SPP dan DAT',
                'created_at' => '2026-06-11 03:02:38',
                'updated_at' => '2026-06-11 04:16:02',
            ],
            [
                'id' => 5,
                'tahun' => '2025/2026',
                'nominal' => 350000,
                'keterangan' => 'kelas 12',
                'created_at' => '2026-06-11 04:21:22',
                'updated_at' => '2026-06-11 04:21:22',
            ],
        ]);
        
        // Re-enable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}