<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Seeder class for the tagihan table.
 * Generated by Laravel DB Craft.
 * Generated on: 2026-06-11 13:32:15
 */
class TagihanTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Disable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        
        // Truncate the table
        DB::table('tagihan')->truncate();
        
        // Insert data in chunks
        DB::table('spp')->insert([
            [
                'id' => 9,
                'siswa_id' => 5,
                'spp_id' => 4,
                'bulan' => 'September',
                'tahun' => 2026,
                'nominal' => 350000,
                'status' => 'Lunas',
                'jatuh_tempo' => '2026-07-11',
                'created_at' => '2026-06-11 03:02:52',
                'updated_at' => '2026-06-11 03:31:07',
            ],
            [
                'id' => 10,
                'siswa_id' => 6,
                'spp_id' => 4,
                'bulan' => 'September',
                'tahun' => 2026,
                'nominal' => 350000,
                'status' => 'Lunas',
                'jatuh_tempo' => '2026-07-11',
                'created_at' => '2026-06-11 03:02:52',
                'updated_at' => '2026-06-11 03:31:08',
            ],
            [
                'id' => 11,
                'siswa_id' => 5,
                'spp_id' => 4,
                'bulan' => 'Maret',
                'tahun' => 2026,
                'nominal' => 350000,
                'status' => 'Lunas',
                'jatuh_tempo' => '2026-06-10',
                'created_at' => '2026-06-11 03:33:30',
                'updated_at' => '2026-06-11 03:42:48',
            ],
            [
                'id' => 12,
                'siswa_id' => 6,
                'spp_id' => 4,
                'bulan' => 'Maret',
                'tahun' => 2026,
                'nominal' => 350000,
                'status' => 'Belum Lunas',
                'jatuh_tempo' => '2026-06-10',
                'created_at' => '2026-06-11 03:33:30',
                'updated_at' => '2026-06-11 03:38:35',
            ],
        ]);
        
        // Re-enable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}