<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Seeder class for the users table.
 * Generated by Laravel DB Craft.
 * Generated on: 2026-06-11 13:32:15
 */
class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Disable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        
        // Truncate the table
        DB::table('users')->truncate();
        
        // Insert data in chunks
        DB::table('tagihan')->insert([
            [
                'id' => 1,
                'username' => 'admin',
                'nis' => null,
                'name' => 'Administrator',
                'email' => 'admin@sekolah.com',
                'email_verified_at' => null,
                'password' => '$2y$12$PsaCvfoKUUHLzFUXISXOEexMzzc5YgOJzfE8RDOn3KovpWphjpo26',
                'remember_token' => null,
                'created_at' => '2026-06-07 11:25:27',
                'updated_at' => '2026-06-07 11:25:27',
                'no_telepon' => null,
                'alamat' => null,
                'role' => 'admin',
                'jenis_kelamin' => null,
                'status_aktif' => 1,
                'kelas_id' => null,
                'jurusan_id' => null,
                'tahun_ajaran' => null,
            ],
            [
                'id' => 5,
                'username' => 'siswa',
                'nis' => 2024001,
                'name' => 'Siswa Baru',
                'email' => 'siswa@example.com',
                'email_verified_at' => null,
                'password' => '$2y$12$pEfbbaA5C5sC8I86RWiUTeuDazCFa5ZH3vmj2vgbx4HiaH1yS2PdS',
                'remember_token' => null,
                'created_at' => '2026-06-07 07:10:33',
                'updated_at' => '2026-06-07 07:10:33',
                'no_telepon' => null,
                'alamat' => null,
                'role' => 'siswa',
                'jenis_kelamin' => 'L',
                'status_aktif' => 1,
                'kelas_id' => null,
                'jurusan_id' => null,
                'tahun_ajaran' => null,
            ],
            [
                'id' => 6,
                'username' => null,
                'nis' => 1234567890,
                'name' => 'Moch Rafi Sidiq',
                'email' => null,
                'email_verified_at' => null,
                'password' => '$2y$12$6DQCiXN3sflXIDycrt/dhuaQgNnPn/mjsD3xPsFB73fnOJ8y5nvCa',
                'remember_token' => null,
                'created_at' => '2026-06-08 09:43:35',
                'updated_at' => '2026-06-08 09:43:35',
                'no_telepon' => 0987654321,
                'alamat' => 'kp. mana aja',
                'role' => 'siswa',
                'jenis_kelamin' => 'L',
                'status_aktif' => 1,
                'kelas_id' => 3,
                'jurusan_id' => 1,
                'tahun_ajaran' => '2024/2025',
            ],
        ]);
        
        // Re-enable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}